//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proba_11
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Квартира.
    /// </summary>
    // *** Start programmer edit section *** (Квартира CustomAttributes)

    // *** End programmer edit section *** (Квартира CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КвартираE", new string[] {
            "НомерКв as \'Название\'"})]
    [View("КвартираL", new string[] {
            "НомерКв as \'Название\'"})]
    public class Квартира : ICSSoft.STORMNET.DataObject
    {
        
        private string fНомерКв;
        
        // *** Start programmer edit section *** (Квартира CustomMembers)

        // *** End programmer edit section *** (Квартира CustomMembers)

        
        /// <summary>
        /// НомерКв.
        /// </summary>
        // *** Start programmer edit section *** (Квартира.НомерКв CustomAttributes)

        // *** End programmer edit section *** (Квартира.НомерКв CustomAttributes)
        [StrLen(255)]
        public virtual string НомерКв
        {
            get
            {
                // *** Start programmer edit section *** (Квартира.НомерКв Get start)

                // *** End programmer edit section *** (Квартира.НомерКв Get start)
                string result = this.fНомерКв;
                // *** Start programmer edit section *** (Квартира.НомерКв Get end)

                // *** End programmer edit section *** (Квартира.НомерКв Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Квартира.НомерКв Set start)

                // *** End programmer edit section *** (Квартира.НомерКв Set start)
                this.fНомерКв = value;
                // *** Start programmer edit section *** (Квартира.НомерКв Set end)

                // *** End programmer edit section *** (Квартира.НомерКв Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КвартираE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КвартираE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КвартираE", typeof(IIS.Proba_11.Квартира));
                }
            }
            
            /// <summary>
            /// "КвартираL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КвартираL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КвартираL", typeof(IIS.Proba_11.Квартира));
                }
            }
        }
    }
}
