//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proba_11
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// НомерДом.
    /// </summary>
    // *** Start programmer edit section *** (НомерДом CustomAttributes)

    // *** End programmer edit section *** (НомерДом CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("НомерДомE", new string[] {
            "Назв"})]
    [View("НомерДомL", new string[] {
            "Назв"})]
    public class НомерДом : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазв;
        
        private IIS.Proba_11.Этаж fЭтаж;
        
        // *** Start programmer edit section *** (НомерДом CustomMembers)

        // *** End programmer edit section *** (НомерДом CustomMembers)

        
        /// <summary>
        /// Назв.
        /// </summary>
        // *** Start programmer edit section *** (НомерДом.Назв CustomAttributes)

        // *** End programmer edit section *** (НомерДом.Назв CustomAttributes)
        [StrLen(255)]
        public virtual string Назв
        {
            get
            {
                // *** Start programmer edit section *** (НомерДом.Назв Get start)

                // *** End programmer edit section *** (НомерДом.Назв Get start)
                string result = this.fНазв;
                // *** Start programmer edit section *** (НомерДом.Назв Get end)

                // *** End programmer edit section *** (НомерДом.Назв Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (НомерДом.Назв Set start)

                // *** End programmer edit section *** (НомерДом.Назв Set start)
                this.fНазв = value;
                // *** Start programmer edit section *** (НомерДом.Назв Set end)

                // *** End programmer edit section *** (НомерДом.Назв Set end)
            }
        }
        
        /// <summary>
        /// НомерДом.
        /// </summary>
        // *** Start programmer edit section *** (НомерДом.Этаж CustomAttributes)

        // *** End programmer edit section *** (НомерДом.Этаж CustomAttributes)
        [PropertyStorage(new string[] {
                "Этаж"})]
        [NotNull()]
        public virtual IIS.Proba_11.Этаж Этаж
        {
            get
            {
                // *** Start programmer edit section *** (НомерДом.Этаж Get start)

                // *** End programmer edit section *** (НомерДом.Этаж Get start)
                IIS.Proba_11.Этаж result = this.fЭтаж;
                // *** Start programmer edit section *** (НомерДом.Этаж Get end)

                // *** End programmer edit section *** (НомерДом.Этаж Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (НомерДом.Этаж Set start)

                // *** End programmer edit section *** (НомерДом.Этаж Set start)
                this.fЭтаж = value;
                // *** Start programmer edit section *** (НомерДом.Этаж Set end)

                // *** End programmer edit section *** (НомерДом.Этаж Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "НомерДомE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НомерДомE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НомерДомE", typeof(IIS.Proba_11.НомерДом));
                }
            }
            
            /// <summary>
            /// "НомерДомL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НомерДомL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НомерДомL", typeof(IIS.Proba_11.НомерДом));
                }
            }
        }
    }
}
