//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proba_11
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Этаж.
    /// </summary>
    // *** Start programmer edit section *** (Этаж CustomAttributes)

    // *** End programmer edit section *** (Этаж CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЭтажE", new string[] {
            "Номер"})]
    [View("ЭтажL", new string[] {
            "Номер"})]
    public class Этаж : ICSSoft.STORMNET.DataObject
    {
        
        private string fНомер;
        
        // *** Start programmer edit section *** (Этаж CustomMembers)

        // *** End programmer edit section *** (Этаж CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Этаж.Номер CustomAttributes)

        // *** End programmer edit section *** (Этаж.Номер CustomAttributes)
        [StrLen(255)]
        public virtual string Номер
        {
            get
            {
                // *** Start programmer edit section *** (Этаж.Номер Get start)

                // *** End programmer edit section *** (Этаж.Номер Get start)
                string result = this.fНомер;
                // *** Start programmer edit section *** (Этаж.Номер Get end)

                // *** End programmer edit section *** (Этаж.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Этаж.Номер Set start)

                // *** End programmer edit section *** (Этаж.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Этаж.Номер Set end)

                // *** End programmer edit section *** (Этаж.Номер Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЭтажE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЭтажE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЭтажE", typeof(IIS.Proba_11.Этаж));
                }
            }
            
            /// <summary>
            /// "ЭтажL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЭтажL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЭтажL", typeof(IIS.Proba_11.Этаж));
                }
            }
        }
    }
}
